databases:
  - name: Spotipie
    user: allonnam96
    plan: free
    region: ohio

services:
  - type: web
    name: Spotipie
    plan: free
    region: ohio
    branch: main
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Spotipie-database
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
